name: '[Git] Create New Branch'

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Name of the new branch'
        required: true
        type: string
      base_branch:
        description: 'Branch to create from (default: main)'
        required: false
        default: 'main'
        type: string

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.base_branch }}

      - name: Set Git identity to actor
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create new branch
        run: |
          git checkout -b ${{ github.event.inputs.branch_name }}

      - name: Push new branch using token
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.event.inputs.branch_name }}
