name: Release Solution to Production

on:
  workflow_call:
    inputs:
      solution_name:
        required: true
        type: string
      BUILD_ENVIRONMENT_URL:
        required: true
        type: string
      PRODUCTION_ENVIRONMENT_URL:
        required: true
        type: string
      CLIENT_ID:
        required: true
        type: string
      TENANT_ID:
        required: true
        type: string
    secrets:
      envSecret:
        required: true

jobs:
  release-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Create output directory
        run: mkdir -p out/solutions

      - name: Export managed solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ inputs.BUILD_ENVIRONMENT_URL }}
          app-id: ${{ inputs.CLIENT_ID }}
          client-secret: ${{ secrets.envSecret }}
          tenant-id: ${{ inputs.TENANT_ID }}
          solution-name: ${{ inputs.solution_name }}
          solution-output-file: out/solutions/${{ inputs.solution_name }}_managed.zip
          managed: true

      - name: Import to production
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ inputs.PRODUCTION_ENVIRONMENT_URL }}
          app-id: ${{ inputs.CLIENT_ID }}
          client-secret: ${{ secrets.envSecret }}
          tenant-id: ${{ inputs.TENANT_ID }}
          solution-file: out/solutions/${{ inputs.solution_name }}_managed.zip
