name: Call Release To Prod Workflow

on:
  release:
    types: [published]

jobs:
  call-release-workflow:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      environment-url: https://orge065b187.crm4.dynamics.com
      app-id: fdfe9ed0-a6d4-44f4-80ed-c4d9f2aaf6d7
      tenant-id: 540a9168-5a7c-42d3-9989-d4d22958d81c
    secrets:
      client-secret: POWERPLATFORMSPN
