name: Release Solution To Prod (Reusable)

on:
  workflow_call:
    inputs:
      environment-url:
        required: true
        type: string
      app-id:
        required: true
        type: string
      tenant-id:
        required: true
        type: string
      client-secret:
        required: true
        type: string

jobs:
  release-solution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Power Platform tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Pack managed solution
        uses: microsoft/powerplatform-actions/pack-solution@v1
        with:
          solution-folder: solutions/ALMLab
          solution-file: out/solutions/ALMLab_managed.zip
          solution-type: Managed

      - name: Import managed solution to production
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ inputs.environment-url }}
          app-id: ${{ inputs.app-id }}
          client-secret: ${{ inputs.client-secret }}
          tenant-id: ${{ inputs.tenant-id }}
          solution-file: out/solutions/ALMLab_managed.zip
