name: Export and Unpack Solution

on:
  workflow_dispatch:

jobs:
  export-solution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Power Platform Tool Installer
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: WhoAmI - Verify connection
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: https://orga129dc5e.crm4.dynamics.com  # Dev
          app-id: fdfe9ed0-a6d4-44f4-80ed-c4d9f2aaf6d7
          client-secret: ${{ secrets.POWERPLATFORMSPN }}
          tenant-id: 540a9168-5a7c-42d3-9989-d4d22958d81c

      - name: Export solution from environment
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: https://orga129dc5e.crm4.dynamics.com  # Dev
          app-id: fdfe9ed0-a6d4-44f4-80ed-c4d9f2aaf6d7
          client-secret: ${{ secrets.POWERPLATFORMSPN }}
          tenant-id: 540a9168-5a7c-42d3-9989-d4d22958d81c
          solution-name: ALMLab
          solution-output-file: out/solutions/ALMLab.zip

      - name: Unpack solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: out/solutions/ALMLab.zip
          solution-folder: solutions/ALMLab
          solution-type: Unmanaged

      - name: Push branch to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="solution-update-$(date +%Y%m%d%H%M%S)"
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b $BRANCH_NAME
          git add solutions/ALMLab
          git reset .github/workflows/export-and-branch-solution.yml || true
          git commit -m "Export and unpack ALMLab solution"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $BRANCH_NAME
