name: release-solution-to-prod-reusable

on:
  workflow_call:
    inputs: 
      solution_name:
        type: string
        default: ALMLab      
      solution_source_folder: 
        type: string
        default: solutions/
      solution_outbound_folder:
        type: string
        default: out/solutions/
      solution_release_folder:
        type: string
        default: out/release/
      BUILD_ENVIRONMENT_URL:
        type: string
        required: true      
      PRODUCTION_ENVIRONMENT_URL: 
        type: string
        required: true
      CLIENT_ID: 
        type: string
        required: true
      TENANT_ID: 
        type: string
        required: true
    secrets:
      envSecret:
        required: true

jobs:
  convert-to-managed:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install PAC CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Pack solution (locally)
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-folder: ${{ inputs.solution_source_folder }}/${{ inputs.solution_name }}
        solution-file: ${{ inputs.solution_outbound_folder }}/${{ inputs.solution_name }}.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged (build env)
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{ inputs.BUILD_ENVIRONMENT_URL }}
        app-id: ${{ inputs.CLIENT_ID }}
        client-secret: ${{ secrets.envSecret }}
        tenant-id: ${{ inputs.TENANT_ID }}
        solution-file: ${{ inputs.solution_outbound_folder }}/${{ inputs.solution_name }}.zip
        force-overwrite: true
        publish-changes: true

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ inputs.BUILD_ENVIRONMENT_URL }}
        app-id: ${{ inputs.CLIENT_ID }}
        client-secret: ${{ secrets.envSecret }}
        tenant-id: ${{ inputs.TENANT_ID }}
        solution-name: ${{ inputs.solution_name }}
        managed: true
        solution-output-file: ${{ inputs.solution_release_folder }}/${{ inputs.solution_name }}_managed.zip

    - name: Upload to GitHub artifacts
      uses: actions/upload-artifact@v4
      with:
        name: managedSolution
        path: ${{ inputs.solution_release_folder }}

  release-to-production:
    needs: [convert-to-managed]
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install PAC CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Download solution from artifact
      uses: actions/download-artifact@v4
      with:
        name: managedSolution
        path: ${{ inputs.solution_release_folder }}

    - name: Import solution to production as managed
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{ inputs.PRODUCTION_ENVIRONMENT_URL }}
        app-id: ${{ inputs.CLIENT_ID }}
        client-secret: ${{ secrets.envSecret }}
        tenant-id: ${{ inputs.TENANT_ID }}
        solution-file: ${{ inputs.solution_release_folder }}/${{ inputs.solution_name }}_managed.zip
        force-overwrite: true
        publish-changes: true
