name: Release Solution to Production

on:
  workflow_call:
    inputs:
      environment-url:
        required: true
        type: string
      app-id:
        required: true
        type: string
      tenant-id:
        required: true
        type: string
    secrets:
      client-secret:
        required: true

jobs:
  release-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Power Platform Tool Installer
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Import solution into production
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ inputs.environment-url }}
          app-id: ${{ inputs.app-id }}
          client-secret: ${{ secrets.client-secret }}
          tenant-id: ${{ inputs.tenant-id }}
          solution-file: out/solutions/ALMLab_managed.zip
